# Generated by Django 3.2.5 on 2021-07-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mdl_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lan', models.CharField(max_length=20, verbose_name='نام زبان')),
            ],
        ),
        migrations.CreateModel(
            name='mdl_participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, verbose_name='شماره همراه')),
                ('date_enter', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ورود')),
                ('date_exit', models.DateTimeField(verbose_name='تاریخ و ساعت خروج')),
                ('birthday', models.DateField(verbose_name='تاریخ تولد')),
                ('jensiat', models.CharField(max_length=20, verbose_name='جنسیت')),
                ('national_number', models.CharField(max_length=10, verbose_name='شماره پاسپورت')),
                ('nationality', models.CharField(max_length=40, verbose_name='ملیت')),
                ('desc_illness', models.TextField(max_length=2000, verbose_name='توضیحات بیماری')),
                ('illness', models.TextField(max_length=40, verbose_name='بیماری')),
                ('num_traveller', models.IntegerField(default=0, verbose_name='تعداد همراهان')),
                ('language', models.ManyToManyField(to='myapp1.mdl_language', verbose_name='زبان ها')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.mdl_participant', verbose_name='سرپرست')),
            ],
        ),
    ]
