# Generated by Django 3.2.5 on 2021-07-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl_participant',
            name='illness',
            field=models.CharField(choices=[('blood pressure', 'فشار خون'), ('diabet', 'دیابت')], max_length=40, verbose_name='بیماری'),
        ),
    ]
