# Generated by Django 3.2.5 on 2021-07-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_alter_mdl_participant_illness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl_participant',
            name='jensiat',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=20, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='mdl_participant',
            name='nationality',
            field=models.CharField(choices=[('iranian', 'ایرانی'), ('other', 'غیر ایرانی')], max_length=40, verbose_name='ملیت'),
        ),
    ]
